### ISSUE TITLE
CherryTrail : Missing support

### ISSUE THREAD

**Issue by oopen** [IntelFsp/FSP#19]
CherryTrail are Airmont based, where Airmont is the 14 nm die shrink of Silvermont

Other Airmont FSP support exist : Braswell

When Silvermont have BayTrail FSP

Braswell OR BayTrail can be used for CherryTrail chips ?

**Comment by shwong1** [comment]
Neither Braswell nor Bay Trail can be used for Cherry Trail.

**Comment by oopen** [comment]
There is no release planned ?

**Comment by nate-desimone** [comment]
Not at this time.

**Comment by nicklasfrahm** [comment]
I was wondering if it would be possible to reopen this? I bought a Rock Pi X, which has an Intel Atom x5-Z8350 and comes with an AMI UEFI BIOS. The issue however is that this does not support netbooting due to the missing driver for the RTL8168. So I am considering to build EDK II for it, but that would require this FSP.
